# This workflow will run the tests for the awpy Python library

name: build

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Checkout csgo library
        uses: actions/checkout@v3
      - name: Installation
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f tests/requirements.txt ]; then pip install -r tests/requirements.txt; fi
      - name: Check formatting with black
        uses: psf/black@stable
      - name: Lint with ruff
        uses: chartboost/ruff-action@v1
      - name: Typecheck with pyright
        uses: jakebailey/pyright-action@v1
      - name: Test with pytest
        run: |
          coverage run -m pytest --durations=10
          coverage report -m
          coverage html
      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: htmlcov/
